version: '3'
services:
  chess_worker:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./chess_worker
    volumes:
      - ./chess_worker:/app
    command: ["pnpm", "run", "test:develop"]
