version: '3'
services:
  chess_worker:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./chess_worker
    volumes:
      - /app/node_modules
      - ./chess_worker:/app
    command: ["pnpm", "run", "test:prod"]
  serv:
    restart: on-failure
    build:
      dockerfile: Dockerfile.test.dev
      context: ./serv
    volumes:
      - /app/node_modules
      - ./serv:/app
    depends_on:
      - chess_worker
    command: ["pnpm", "run", "test:prod"]
