version: '3'
services:
  chess_worker:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./chess_worker
    ports:
      - 5000:5000
    volumes:
      - ./chess_worker:/app
    command: ["pnpm", "run", "dev"]
