version: '3'
services:
  tests:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
