version: '3'
services:
  client:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
    depends_on:
      - chess_worker
  chess_worker:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./chess_worker
    volumes:
      - /app/node_modules
      - ./chess_worker:/app
    ports:
      - 5000:5000
  serv:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./serv
    volumes:
      - /app/node_modules
      - ./serv:/app
    ports:
      - 6942:6942
  test_client:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    command: ["npm", "run", "test"]
  test_cw:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./chess_worker
    volumes:
      - /app/node_modules
      - ./chess_worker:/app
    command: ["pnpm", "run", "test:prod"]
  test_serv:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./serv
    volumes:
      - /app/node_modules
      - ./serv:/app
    command: ["pnpm", "run", "test:prod"]
