version: '3'
services:
  serv:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./serv
    volumes:
      - /app/node_modules
      - ./serv:/app
    ports:
      - 6942:6942
    depends_on:
      - chess_worker
  chess_worker:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./chess_worker
    volumes:
      - /app/node_modules
      - ./chess_worker:/app
    ports:
      - 5000:5000
